name: "check-in"

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
          php-version: 8.1
          tools: composer

      - name: "Install locked dependencies"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Run check-in script"
        env:
          COOKIE_SMZDM: ${{ secrets.COOKIE_SMZDM }}
          PROXY_SOCKS5: ${{ secrets.PROXY_SOCKS5 }}
        run: php check_in.php
